#!/bin/bash

#Add key
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" >> /etc/apt/sources.list.d/docker.list

sudo apt-get -y update
sudo apt-get purge lxc-docker
apt-cache policy docker-engine

sudo apt-get -y update
sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

#Install Docker
sudo apt-get -y update
#sudo apt-get -y install docker-engine
sudo apt-get -y install docker-engine=17.03.1~ce-0~ubuntu-xenial
sudo service docker start

#Install Compose
#sudo curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
#sudo chmod +x /usr/local/bin/docker-compose

#Add user to docker
sudo usermod -aG docker pqadmin

#Install Zip
sudo apt-get install -y zip tree unzip links2 jq

# Install Rancher
cd ~
wget https://releases.rancher.com/cli/v0.6.1/rancher-linux-amd64-v0.6.1.tar.gz
tar xvf rancher-linux-amd64-v0.6.1.tar.gz
cd rancher-v0.6.1
sudo chmod +x rancher
sudo mv rancher /usr/bin
cd ..
rm -fr rancher-v0.6.1
rm rancher-linux-amd64-v0.6.1.tar.gz

# Install Rancher-Compose
wget https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
tar xvf rancher-compose-linux-amd64-v0.12.5.tar.gz
cd rancher-compose-v0.12.5
sudo chmod +x rancher-compose
sudo mv rancher-compose /usr/bin
cd ..
rm -fr rancher-compose-v0.12.5
rm rancher-compose-linux-amd64-v0.12.5.tar.gz

#Install AzureDriver
cd /usr/bin
sudo wget https://github.com/Azure/azurefile-dockervolumedriver/releases/download/v0.5.1/azurefile-dockervolumedriver
sudo chmod +x azurefile-dockervolumedriver

cd /etc/default
sudo wget https://raw.githubusercontent.com/Azure/azurefile-dockervolumedriver/master/contrib/init/systemd/azurefile-dockervolumedriver.default
# This file needs updating
echo "/etc/default/azurefile-dockervolumedriver"
sudo mv azurefile-dockervolumedriver.default azurefile-dockervolumedriver

cd /etc/systemd/system
sudo wget https://raw.githubusercontent.com/Azure/azurefile-dockervolumedriver/master/contrib/init/systemd/azurefile-dockervolumedriver.service

#systemctl daemon-reload
#systemctl enable azurefile-dockervolumedriver
#systemctl start azurefile-dockervolumedriver

